package network.rpcprotocol;

public enum ResponseType {
    OK, ERROR, EMPLOYEE_LOGGED_IN, EMPLOYEE_LOGGED_OUT, SHOWS, FIND_EMPLOYEE_BY_USERNAME, FIND_SHOW_BY_ID, GET_ARTISTS_BY_DATE, SHOW_UPDATED
}
